{"name": "验证错错误登录", "status": "passed", "attachments": [{"source": "e98e4133-4139-40c4-a44c-3305fffbc2cf-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "a7bb27ba-8009-43b3-a589-efc97a367a84-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'19100129'"}, {"name": "pw", "value": "'123456'"}, {"name": "msg", "value": "'账号错误'"}], "start": 1622712887624, "stop": 1622712894167, "uuid": "403a7093-a1d7-42c7-8554-6b0fc0356332", "historyId": "884a4a494b5a990700ff84bf2b8b3754", "testCaseId": "0a157dd46979acb51da04934dbb33d2c", "fullName": "test_login.TestLogin#test_sms_login_error", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MicroWin10-1243"}, {"name": "thread", "value": "6380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}